import { NextResponse } from "next/server";

const lines = [
  "# POS Companion API (current)",
  "",
  "Base URL:",
  "- http://localhost:3000",
  "",
  "Auth:",
  "- Authorization: Bearer <ACCESS_TOKEN>",
  "",
  "Response envelope:",
  "```json",
  "{\"success\":true,\"message\":\"OK\",\"data\":{}}",
  "```",
  "",
  "------------------------------",
  "## Auth",
  "",
  "### POST /api/auth/register",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/register \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"password\":\"123456\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Registered\",\"data\":{\"id\":\"USER_ID\",\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"role\":\"OWNER\",\"storeIds\":[]}}",
  "```",
  "",
  "### POST /api/auth/login",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/login \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"email\":\"owner@mail.com\",\"password\":\"123456\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Logged in\",\"data\":{\"user\":{\"id\":\"USER_ID\",\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"role\":\"OWNER\",\"storeIds\":[\"STORE_ID\"]},\"tokens\":{\"accessToken\":\"<JWT>\",\"refreshToken\":\"<JWT>\"}}}",
  "```",
  "",
  "### POST /api/auth/reissue",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/reissue \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "Response: same as login (new tokens, updated storeIds)",
  "",
  "------------------------------",
  "## Stores",
  "",
  "### POST /api/stores",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/stores \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Toko A\",\"address\":\"Jl. Example\",\"phone\":\"081234\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Created\",\"data\":{\"id\":\"STORE_ID\",\"name\":\"Toko A\",\"address\":\"Jl. Example\",\"phone\":\"081234\",\"isActive\":true,\"createdBy\":\"USER_ID\"}}",
  "```",
  "",
  "### GET /api/stores/my",
  "Request:",
  "```bash",
  "curl http://localhost:3000/api/stores/my \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "",
  "### PATCH /api/stores/:id",
  "Request:",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/stores/STORE_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Toko A Updated\"}'",
  "```",
  "",
  "------------------------------",
  "## Cashiers",
  "",
  "### POST /api/stores/:id/cashiers",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/stores/STORE_ID/cashiers \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Kasir 1\",\"email\":\"kasir1@mail.com\",\"password\":\"123456\"}'",
  "```",
  "",
  "### GET /api/stores/:id/cashiers",
  "```bash",
  "curl http://localhost:3000/api/stores/STORE_ID/cashiers \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "",
  "### PATCH /api/stores/:id/cashiers/:userId",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/stores/STORE_ID/cashiers/CASHIER_USER_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"isActive\":false}'",
  "```",
  "",
  "------------------------------",
  "## Products",
  "",
  "### POST /api/products (create)",
  "```bash",
  "curl -X POST http://localhost:3000/api/products \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"name\":\"Kopi\",\"sku\":\"SKU-001\",\"price\":12000,\"stock\":10,\"minimumStock\":2,\"primaryImageUrl\":\"/uploads/x.png\"}'",
  "```",
  "",
  "### POST /api/products/list (list/search per store)",
  "```bash",
  "curl -X POST http://localhost:3000/api/products/list \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"q\":\"kop\"}'",
  "```",
  "",
  "### PATCH /api/products/:id",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/products/PRODUCT_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"price\":13000,\"isActive\":true}'",
  "```",
  "",
  "### POST /api/products/:id/stock",
  "```bash",
  "curl -X POST http://localhost:3000/api/products/PRODUCT_ID/stock \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"delta\":-1}'",
  "```",
  "",
  "------------------------------",
  "## Transactions",
  "",
  "### POST /api/transactions (create)",
  "Note: invoiceNumber optional (server will generate if omitted)",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"paymentMethod\":\"CASH\",\"items\":[{\"productId\":\"PRODUCT_ID\",\"qty\":2,\"price\":12000}]}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Created\",\"data\":{\"id\":\"TX_ID\",\"storeId\":\"STORE_ID\",\"invoiceNumber\":\"INV-XXXX-YYYYMMDD-0001\",\"items\":[{\"productId\":\"PRODUCT_ID\",\"name\":\"Kopi\",\"sku\":\"SKU-001\",\"qty\":2,\"price\":12000,\"lineTotal\":24000}],\"totalAmount\":24000,\"paymentMethod\":\"CASH\",\"cashierId\":\"USER_ID\",\"createdAt\":\"2026-02-10T00:00:00.000Z\"}}",
  "```",
  "",
  "### POST /api/transactions/today",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions/today \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":100}'",
  "```",
  "",
  "### POST /api/transactions/history",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions/history \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"from\":\"2026-02-01T00:00:00.000Z\",\"to\":\"2026-02-10T23:59:59.999Z\"}'",
  "```",
  "",
  "------------------------------",
  "## Dashboard",
  "",
  "### POST /api/dashboard/today",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/today \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\"}'",
  "```",
  "",
  "### POST /api/dashboard/low-stock",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/low-stock \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":20}'",
  "```",
  "",
  "### POST /api/dashboard/recent-transactions",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/recent-transactions \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":10}'",
  "```",
  "",
  "------------------------------",
  "## Uploads",
  "",
  "### POST /api/uploads",
  "Note: On Vercel, configure CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET.",
  "```bash",
  "curl -X POST http://localhost:3000/api/uploads \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -F file=@/path/to/image.png",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Uploaded\",\"data\":{\"url\":\"https://res.cloudinary.com/<cloud>/image/upload/<file>.png\"}}",
  "```",
  "",
  "------------------------------",
  "## Admin utility",
  "",
  "### GET /api/users",
  "### POST /api/users",
  "### GET /api/categories",
  "### POST /api/categories",
  "### PATCH /api/categories/:id",
];

export const GET = async () => {
  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
};
