import { NextResponse } from "next/server";

const lines = [
  "# POS Companion API (current)",
  "",
  "Base URL:",
  "- http://localhost:3000",
  "",
  "Auth:",
  "- Authorization: Bearer <ACCESS_TOKEN>",
  "",
  "Response envelope:",
  "```json",
  "{\"success\":true,\"message\":\"OK\",\"data\":{}}",
  "```",
  "",
  "------------------------------",
  "## Auth",
  "",
  "### POST /api/auth/register",
  "Body schema:",
  "```ts",
  "{",
  "  name: string; // required, min 2",
  "  email: string; // required, email format",
  "  password: string; // required, min 6",
  "}",
  "```",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/register \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"password\":\"123456\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Registered\",\"data\":{\"id\":\"USER_ID\",\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"role\":\"OWNER\",\"storeIds\":[]}}",
  "```",
  "",
  "### POST /api/auth/login",
  "Body schema:",
  "```ts",
  "{",
  "  email: string; // required, email format",
  "  password: string; // required, min 1",
  "}",
  "```",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/login \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"email\":\"owner@mail.com\",\"password\":\"123456\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Logged in\",\"data\":{\"user\":{\"id\":\"USER_ID\",\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"role\":\"OWNER\",\"storeIds\":[\"STORE_ID\"]},\"tokens\":{\"accessToken\":\"<JWT>\",\"refreshToken\":\"<JWT>\"}}}",
  "```",
  "",
  "### POST /api/auth/reissue",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/auth/reissue \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "Response: same as login (new tokens, updated storeIds)",
  "",
  "### GET /api/auth/me (debug token)",
  "```bash",
  "curl http://localhost:3000/api/auth/me \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"OK\",\"data\":{\"sub\":\"USER_ID\",\"role\":\"OWNER\",\"storeIds\":[\"STORE_ID\"]}}",
  "```",
  "",
  "### GET /api/debug (debug routes + env presence)",
  "```bash",
  "curl http://localhost:3000/api/debug \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "",
  "------------------------------",
  "## Stores",
  "",
  "### POST /api/stores",
  "Body schema:",
  "```ts",
  "{",
  "  name: string; // required, min 2",
  "  address?: string; // optional, min 1",
  "  phone?: string; // optional, min 1",
  "}",
  "```",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/stores \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Toko A\",\"address\":\"Jl. Example\",\"phone\":\"081234\"}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Created\",\"data\":{\"store\":{\"id\":\"STORE_ID\",\"name\":\"Toko A\",\"address\":\"Jl. Example\",\"phone\":\"081234\",\"isActive\":true,\"createdBy\":\"USER_ID\"},\"auth\":{\"user\":{\"id\":\"USER_ID\",\"name\":\"Owner\",\"email\":\"owner@mail.com\",\"role\":\"OWNER\",\"storeIds\":[\"STORE_ID\"]},\"tokens\":{\"accessToken\":\"<JWT>\",\"refreshToken\":\"<JWT>\"}}}}",
  "```",
  "",
  "### GET /api/stores/my",
  "Request:",
  "```bash",
  "curl http://localhost:3000/api/stores/my \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "",
  "### PATCH /api/stores/:id",
  "Body schema:",
  "```ts",
  "{",
  "  name?: string; // optional, min 2",
  "  address?: string | null; // optional",
  "  phone?: string | null; // optional",
  "  isActive?: boolean; // optional",
  "}",
  "```",
  "Request:",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/stores/STORE_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Toko A Updated\"}'",
  "```",
  "",
  "------------------------------",
  "## Cashiers",
  "",
  "### POST /api/stores/:id/cashiers",
  "Body schema:",
  "```ts",
  "{",
  "  name: string; // required, min 2",
  "  email: string; // required, email format",
  "  password: string; // required, min 6",
  "}",
  "```",
  "Request:",
  "```bash",
  "curl -X POST http://localhost:3000/api/stores/STORE_ID/cashiers \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"name\":\"Kasir 1\",\"email\":\"kasir1@mail.com\",\"password\":\"123456\"}'",
  "```",
  "",
  "### GET /api/stores/:id/cashiers",
  "```bash",
  "curl http://localhost:3000/api/stores/STORE_ID/cashiers \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\"",
  "```",
  "",
  "### PATCH /api/stores/:id/cashiers/:userId",
  "Body schema:",
  "```ts",
  "{",
  "  isActive?: boolean; // optional",
  "  password?: string; // optional, min 6",
  "}",
  "```",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/stores/STORE_ID/cashiers/CASHIER_USER_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"isActive\":false}'",
  "```",
  "",
  "------------------------------",
  "## Products",
  "",
  "### POST /api/products (create)",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  name: string; // required, min 2",
  "  sku: string; // required, min 1",
  "  categoryId?: string | null;",
  "  unit?: string; // min 1",
  "  price: number; // required, >= 0",
  "  stock?: number;",
  "  minimumStock?: number;",
  "  primaryImageUrl?: string | null; // url",
  "  imageUrls?: string[]; // each url",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/products \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"name\":\"Kopi\",\"sku\":\"SKU-001\",\"price\":12000,\"stock\":10,\"minimumStock\":2,\"primaryImageUrl\":\"/uploads/x.png\"}'",
  "```",
  "",
  "### POST /api/products/list (list/search per store)",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  q?: string; // optional, min 1",
  "  categoryId?: string; // optional, min 1",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/products/list \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"q\":\"kop\"}'",
  "```",
  "",
  "### PATCH /api/products/:id",
  "Body schema:",
  "```ts",
  "{",
  "  name?: string; // min 2",
  "  sku?: string; // min 1",
  "  categoryId?: string | null;",
  "  unit?: string; // min 1",
  "  price?: number; // >= 0",
  "  stock?: number;",
  "  minimumStock?: number;",
  "  primaryImageUrl?: string | null; // url",
  "  imageUrls?: string[]; // each url",
  "  isActive?: boolean;",
  "}",
  "```",
  "```bash",
  "curl -X PATCH http://localhost:3000/api/products/PRODUCT_ID \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"price\":13000,\"isActive\":true}'",
  "```",
  "",
  "### POST /api/products/:id/stock",
  "Body schema:",
  "```ts",
  "{",
  "  delta: number; // required",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/products/PRODUCT_ID/stock \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"delta\":-1}'",
  "```",
  "",
  "------------------------------",
  "## Transactions",
  "",
  "### POST /api/transactions (create)",
  "Note: invoiceNumber optional (server will generate if omitted)",
  "Money fields are integers in minor units (e.g. pence/cents/rupiah).",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  invoiceNumber?: string; // optional, min 1",
  "  paymentMethod: string; // required, min 1",
  "  items: Array<{ productId: string; qty: number; price: number }>; // required, min 1 item",
  "  // items[].qty must be integer >= 1",
  "  // items[].price must be integer >= 0 (minor units)",
  "  discount?: { type: 'AMOUNT' | 'PERCENT'; amount?: number; percent?: number };",
  "  // discount.type=AMOUNT: amount required (int >= 0)",
  "  // discount.type=PERCENT: percent required (0..100)",
  "  tax?: { rate: number; inclusive?: boolean }; // rate: 0..1 (e.g. 0.2 for 20%)",
  "  // tax.inclusive=false => add tax on top; inclusive=true => prices include tax",
  "  cashReceived?: number; // optional int >= 0 (used when paymentMethod=CASH)",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"paymentMethod\":\"CASH\",\"cashReceived\":50000,\"discount\":{\"type\":\"PERCENT\",\"percent\":10},\"tax\":{\"rate\":0.11,\"inclusive\":false},\"items\":[{\"productId\":\"PRODUCT_ID\",\"qty\":2,\"price\":12000}]}'",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Created\",\"data\":{\"id\":\"TX_ID\",\"storeId\":\"STORE_ID\",\"invoiceNumber\":\"INV-XXXX-YYYYMMDD-0001\",\"items\":[{\"productId\":\"PRODUCT_ID\",\"name\":\"Kopi\",\"sku\":\"SKU-001\",\"qty\":2,\"price\":12000,\"lineTotal\":24000}],\"subtotal\":24000,\"discount\":{\"type\":\"PERCENT\",\"amount\":null,\"percent\":10},\"discountAmount\":2400,\"tax\":{\"rate\":0.11,\"inclusive\":false},\"taxAmount\":2376,\"totalAmount\":23976,\"cashReceived\":50000,\"change\":26024,\"paymentMethod\":\"CASH\",\"cashierId\":\"USER_ID\",\"createdAt\":\"2026-02-10T00:00:00.000Z\"}}",
  "```",
  "",
  "### POST /api/transactions/today",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  limit?: number; // optional, integer 1..500",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions/today \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":100}'",
  "```",
  "",
  "### POST /api/transactions/history",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  from?: string; // optional, ISO datetime",
  "  to?: string; // optional, ISO datetime",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/transactions/history \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"from\":\"2026-02-01T00:00:00.000Z\",\"to\":\"2026-02-10T23:59:59.999Z\"}'",
  "```",
  "",
  "------------------------------",
  "## Dashboard",
  "",
  "### POST /api/dashboard/today",
  "Body schema:",
  "```ts",
  "{ storeId: string; // required, min 1 }",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/today \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\"}'",
  "```",
  "",
  "### POST /api/dashboard/low-stock",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  limit?: number; // optional, integer 1..500",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/low-stock \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":20}'",
  "```",
  "",
  "### POST /api/dashboard/recent-transactions",
  "Body schema:",
  "```ts",
  "{",
  "  storeId: string; // required, min 1",
  "  limit?: number; // optional, integer 1..500",
  "}",
  "```",
  "```bash",
  "curl -X POST http://localhost:3000/api/dashboard/recent-transactions \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -H \"content-type: application/json\" \\",
  "  -d '{\"storeId\":\"STORE_ID\",\"limit\":10}'",
  "```",
  "",
  "------------------------------",
  "## Uploads",
  "",
  "### POST /api/uploads",
  "Note: On Vercel, configure CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET.",
  "```bash",
  "curl -X POST http://localhost:3000/api/uploads \\",
  "  -H \"authorization: Bearer <ACCESS_TOKEN>\" \\",
  "  -F file=@/path/to/image.png",
  "```",
  "Response (example):",
  "```json",
  "{\"success\":true,\"message\":\"Uploaded\",\"data\":{\"url\":\"https://res.cloudinary.com/<cloud>/image/upload/<file>.png\"}}",
  "```",
  "",
  "------------------------------",
  "## Admin utility",
  "",
  "### GET /api/users",
  "### POST /api/users",
  "### GET /api/categories",
  "### POST /api/categories",
  "### PATCH /api/categories/:id",
  "### DELETE /api/categories/:id",
];

export const GET = async () => {
  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
};
